<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class ContactRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'name'    => 'required',
            'email'   => 'required|email',
            'subject' => 'required|min:5|max:20',
            'message' => 'required|min:10|max:50',
        ];
    }
    public function attributes()
    {
        //return parent::attributes(); // TODO: Change the autogenerated stub
        return [
            'name' => 'имя',
            'email' => 'электронная почта'
        ];
    }

    public function messages()
    {
        //return parent::messages(); // TODO: Change the autogenerated stub
        return [
            'name.required' => 'Поле имя является обязательным',
            'subject.required' => 'Поле тема является обязательным',
            'email.required' => 'Поле электронная почта является обязательным',
            'message.required' => 'Поле сообщения является обязательным',
        ];
    }
}
